# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default='Blah blah blah'),
        ),
    ]
